"""empty message

Revision ID: d2f33981ab92
Revises: ea059009279c
Create Date: 2019-12-03 16:51:10.639907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f33981ab92'
down_revision = 'ea059009279c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answerer_id', sa.Integer(), nullable=True))
    op.drop_constraint('question_answer_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'user', ['answerer_id'], ['id'])
    op.drop_column('question', 'answer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_answer_id_fkey', 'question', 'user', ['answer_id'], ['id'])
    op.drop_column('question', 'answerer_id')
    # ### end Alembic commands ###
